include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_met
  errors:
    todo: ignore

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-first
    - prefer-last
    - always-remove-listener
    - avoid-returning-widgets
