name: fun_with_piano 
description: Test how well do you know chords on piano

publish_to: 'none' 

version: 1.0.3+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_midi:
    git:
      url: https://github.com/akvus/flutter_midi.git
      ref: 6be437d97e0b090be3997cb082c35ea94ffa7c10
  flutter_midi_command: 0.4.7
  flutter_riverpod: 1.0.4
  freezed_annotation: 2.0.3
  piano: 
    git:
      url: https://github.com/akvus/flutter_piano_widget.git
      ref: 62b26e21ef00f900f80e007e7ce3c424737e0c2f
  time: 2.1.0

dev_dependencies:
  build_runner: 2.1.10
  dart_code_metrics:  4.15.1
  flutter_lints:  2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.0.3+1
  mocktail: 0.3.0
  test: 1.21.1

flutter:
  uses-material-design: true
  assets:
    - assets/piano_font.sf2


