name: fun_with_piano 
description: Test how well do you know chords on piano

publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_midi_command: 0.4.5
  flutter_riverpod: 1.0.3
  freezed_annotation: 2.0.1
  piano: 
    git:
      url: https://github.com/akvus/flutter_piano_widget.git
      ref: 5439c421590912f149283068d0429bd7813f8850
  time: 2.1.0

dependency_overrides:
  test_api: 0.4.9

dev_dependencies:
  build_runner: 2.1.7
  dart_code_metrics:  4.15.0
  flutter_lints:  1.0.4
  flutter_test:
    sdk: flutter
  freezed: 2.0.2
  mocktail: 0.3.0
  test: 1.21.1

flutter:
  uses-material-design: true


