name: piano_chords_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command: 0.4.5
  flutter_riverpod: 1.0.3
  freezed_annotation: 2.0.1
  piano: 
    git:
      url: https://github.com/akvus/flutter_piano_widget.git
      ref: 5439c421590912f149283068d0429bd7813f8850
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: 2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.0.2

flutter:
  uses-material-design: true


