name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
